# Generated by Django 5.0.4 on 2024-04-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
